#!/bin/bash
# disable beep
xset -b

# set keyboard (in x) to gb and switch capslook for control
# setxkbmap -layout gb -option ctrl:nocaps

# start compositor for fancy visuals
picom &

# unclutter - hide the mouse cursor
unclutter --jitter 10 --ignore-scrolling --start-hidden --fork

# notrogen for wallpaper
nitrogen --restore &

#spotifyd &

# start Qtime WM
qtile start
